hostname: leaf2
is_deployed: true
router_bgp:
  as: '65101'
  router_id: 192.0.255.4
  distance:
    external_routes: 20
    internal_routes: 200
    local_routes: 200
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  graceful_restart:
    enabled: true
    restart_time: 300
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65101'
    next_hop_self: true
    description: leaf1
    maximum_routes: 12000
    send_community: all
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    maximum_routes: 12000
    send_community: all
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    ebgp_multihop: 3
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  neighbors:
  - ip_address: 10.255.252.2
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    peer: leaf1
    description: leaf1_Vlan4093
  - ip_address: 172.31.255.4
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: spine1
    description: spine1_Ethernet3/1
  - ip_address: 172.31.255.6
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: spine2
    description: spine2_Ethernet3/1
  - ip_address: 192.0.255.1
    peer_group: EVPN-OVERLAY-PEERS
    peer: spine1
    description: spine1_Loopback0
    remote_as: '65001'
  - ip_address: 192.0.255.2
    peer_group: EVPN-OVERLAY-PEERS
    peer: spine2
    description: spine2_Loopback0
    remote_as: '65001'
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  vrfs:
  - name: IRB-VRF01
    rd: 192.0.255.4:11
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '11:11'
      export:
      - address_family: evpn
        route_targets:
        - '11:11'
    router_id: 192.0.255.4
    redistribute:
      connected:
        enabled: true
        route_map: RM-CONN-2-BGP-VRFS
    neighbors:
    - ip_address: 10.255.252.2
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: leaf1_Vlan3010
  vlans:
  - id: 101
    tenant: IRB-USE-CASE
    rd: 192.0.255.4:10101
    route_targets:
      both:
      - 10101:10101
    redistribute_routes:
    - learned
  - id: 102
    tenant: IRB-USE-CASE
    rd: 192.0.255.4:10102
    route_targets:
      both:
      - 10102:10102
    redistribute_routes:
    - learned
  - id: 200
    tenant: L2VLAN-USE-CASE
    rd: 192.0.255.4:2200
    route_targets:
      both:
      - 2200:2200
    redistribute_routes:
    - learned
static_routes:
- vrf: default
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.73.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
transceiver_qsfp_default_mode_4x10: true
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
  no_spanning_tree_vlan: 4093-4094
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
- name: arista
  privilege: 15
  role: network-admin
  sha512_password: $6$7WhvEi5Ce5f5Ut3z$Ethmha7rb710RKsaVteusVOuNP1Utfjzse58xxbgiZp4MF0fp7BX5lAw8yBgv/HWCihVomuCSrsJx8wKnJ7Tm1
- name: tom
  privilege: 15
  role: network-admin
  sha512_password: $6$TyWn7NeXe/vBRl1t$S4fEOkPmpTGz7TLHCzDNP8D2UfpO3ciC2MuGmCaFMVF3B7zt9KSnt9yq99y69XBIY1HV/kO4QjOk32yRQOru5.
vrfs:
- name: default
  ip_routing: false
- name: IRB-VRF01
  tenant: IRB-USE-CASE
  ip_routing: true
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: default
  ip_address: 192.168.73.14/24
  gateway: 192.168.73.1
  type: oob
mac_address_table:
  aging_time: 300
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
eos_cli: "interface Management1\n   no lldp transmit"
vlans:
- id: 4093
  tenant: system
  name: MLAG_L3
  trunk_groups:
  - MLAG
- id: 4094
  tenant: system
  name: MLAG
  trunk_groups:
  - MLAG
- id: 101
  name: IRB-VRF01-VL101
  tenant: IRB-USE-CASE
- id: 102
  name: IRB-VRF01-VL102
  tenant: IRB-USE-CASE
- id: 3010
  name: MLAG_L3_VRF_IRB-VRF01
  trunk_groups:
  - MLAG
  tenant: IRB-USE-CASE
- id: 200
  name: L2VLAN-VL200
  tenant: L2VLAN-USE-CASE
vlan_interfaces:
- name: Vlan4093
  description: MLAG_L3
  shutdown: false
  mtu: 1500
  ip_address: 10.255.252.3/31
- name: Vlan4094
  description: MLAG
  shutdown: false
  no_autostate: true
  mtu: 1500
  ip_address: 10.255.252.1/31
- name: Vlan101
  tenant: IRB-USE-CASE
  tags:
  - rack01
  description: IRB-VRF01-VL101
  shutdown: false
  ip_address_virtual: 10.1.1.1/24
  vrf: IRB-VRF01
- name: Vlan102
  tenant: IRB-USE-CASE
  tags:
  - rack01
  description: IRB-VRF01-VL102
  shutdown: false
  ip_address_virtual: 10.1.2.1/24
  vrf: IRB-VRF01
- name: Vlan3010
  tenant: IRB-USE-CASE
  type: underlay_peering
  shutdown: false
  description: MLAG_L3_VRF_IRB-VRF01
  vrf: IRB-VRF01
  mtu: 1500
  ip_address: 10.255.252.3/31
port_channel_interfaces:
- name: Port-Channel551
  description: MLAG_leaf1_Port-Channel551
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
  shutdown: false
- name: Port-Channel4
  description: PortChanne1
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 1-4094
  mlag: 4
ethernet_interfaces:
- name: Ethernet55/1
  peer: leaf1
  peer_interface: Ethernet55/1
  peer_type: mlag_peer
  description: MLAG_leaf1_Ethernet55/1
  shutdown: false
  channel_group:
    id: 551
    mode: active
- name: Ethernet56/1
  peer: leaf1
  peer_interface: Ethernet56/1
  peer_type: mlag_peer
  description: MLAG_leaf1_Ethernet56/1
  shutdown: false
  channel_group:
    id: 551
    mode: active
- name: Ethernet53/1
  peer: spine1
  peer_interface: Ethernet3/1
  peer_type: spine
  description: P2P_spine1_Ethernet3/1
  shutdown: false
  mtu: 1500
  switchport:
    enabled: false
  ip_address: 172.31.255.5/31
- name: Ethernet54/1
  peer: spine2
  peer_interface: Ethernet3/1
  peer_type: spine
  description: P2P_spine2_Ethernet3/1
  shutdown: false
  mtu: 1500
  switchport:
    enabled: false
  ip_address: 172.31.255.7/31
- name: Ethernet4
  peer: host1
  peer_interface: Eth2
  peer_type: server
  port_profile: TRUNK_PROFILE
  description: SERVER_host1_Eth2
  shutdown: false
  channel_group:
    id: 4
    mode: active
- name: Ethernet5
  peer: host2
  peer_interface: Eth2
  peer_type: server
  port_profile: TRUNK_PROFILE
  description: SERVER_host2_Eth2
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 1-4094
mlag_configuration:
  domain_id: pod1
  local_interface: Vlan4094
  peer_address: 10.255.252.0
  peer_link: Port-Channel551
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - origin incomplete
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-CONN-2-BGP-VRFS
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - ip address prefix-list PL-MLAG-PEER-VRFS
  - sequence: 20
    type: permit
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.0.255.4/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.0.254.3/32
- name: Loopback100
  description: DIAG_VRF_IRB-VRF01
  shutdown: false
  vrf: IRB-VRF01
  ip_address: 10.255.1.4/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.0.255.0/24 eq 32
  - sequence: 20
    action: permit 192.0.254.0/24 eq 32
- name: PL-MLAG-PEER-VRFS
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.252.2/31
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
vxlan_interface:
  vxlan1:
    description: leaf2_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback1
      virtual_router_encapsulation_mac_address: mlag-system-id
      vlans:
      - id: 101
        vni: 10101
      - id: 102
        vni: 10102
      - id: 200
        vni: 2200
      vrfs:
      - name: IRB-VRF01
        vni: 11
virtual_source_nat_vrfs:
- name: IRB-VRF01
  ip_address: 10.255.1.4
metadata:
  platform: CEOS_FAKE_HW
